export const SITE = {
  website: "https://milkor.dev",
  author: "Milko Rodríguez",
  profile: "https://milkor.dev",
  desc: "Exploring AI, biology & epistemology. Bridging machine learning with science and meaning.",
  title: "@MilkoRodriguez",
  ogImage: "/assets/milko-avatar.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutos
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/milkorodriguez/astro-paper/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Lima",
} as const;

export const TAGS = [
  "Bioinformatics",
  "Genomics",
  "Proteomics",
  "Systems Biology",
  "Protein Structure Prediction",
  "Deep Learning",
  "ML for Science",
  "AlphaFold",
  "Computational Biology",
  "Neuroscience",
  "Foundation Models",
  "Epistemology",
  "Philosophy of Science",
  "AI & Biology",
  "Tutorials",
  "Research Notes",
];
